name: pylinter
on:
  push:
    branches: [ main ]
    paths:
    - 'factorial.py'
    - 'lint_test.py'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Test information
        run: echo "The name of the branch is ${{ github.ref }}"
      - name: Check out repostitory code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyling
      - name: Lint with pylint
        run: |
          python lint_test.py
      - name: Build container
        run: |
          echo "Building docker container.."
          sleep 60
          echo "Docker container built successfully"
      - name: Deploy
        run: |
          echo "Deploying to out imaginary cluster"
          sleep 60
          echo "App has been deployed successfully"
      - run: echo "This job's status is ${{ job.status }}"
